version: '3'
services:
  gremlin-server-test:
    container_name: chirp_gremlin_test
    image: tinkerpop/gremlin-server
    volumes:
      - ./conf:/opt/gremlin-server/conf_local
    ports:
      - 8190:8182
    command: ./conf_local/gremlin-server.yaml
    networks:
      - local-gremlin-test
networks:
  local-gremlin-test:
