version: '3'
services:
  gremlin-server:
    container_name: chirp_gremlin
    image: tinkerpop/gremlin-server
    volumes:
      - ./conf:/opt/gremlin-server/conf_local
    ports:
      - 8182:8182
    command: ./conf_local/gremlin-server.yaml
    networks:
      - local-gremlin
networks:
  local-gremlin:
